### ISSUE TITLE
Add export feature for charts

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/CompuMaster.Excel#4]
## Feature request
Excel charts must be exportable

## Considerations
* Export features are limited by engine and OS platform

## ToDos
* [ ] MS Excel engine
  * [ ] Windows platform
  * [ ] Non-windows platform
    * NOT supported by engine
* [ ] FreeSpireXls engine
  * [ ] Windows platform
  * [ ] Non-windows platform
    * NOT supported by engine
* [ ] Epplus engine
  * NOT supported by engine
