### ISSUE TITLE
Excel calculation bug documentation / regression tests

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/CompuMaster.Excel#5]
## ToDos
* [ ] Add more documentation on this (common design) bug
* [ ] Add unit test for bug (Assert.Ignore for bug exists, Assert.Pass for bug solved/not existing)
* [ ] Create tickets at manufacturer support sites and reference them from here

**Comment by jochenwezel** [comment]
* [ ] ToDo: check if issue still exists in newer/newest Epplus versions
